# fly.toml app configuration file generated for cartcrafters on 2023-08-15T13:18:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cartcrafters"
primary_region = "yyz"

[build]
image = "ghcr.io/ksmarty/cartcrafters:main"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
