import model.User;
import org.hsqldb.jdbc.JDBCDataSource;
import org.javalite.activejdbc.connection_config.ConnectionJdbcConfig;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import static org.javalite.activejdbc.Base.withDb;

public class DB {
    static final String DB_URL = "jdbc:hsqldb:mem:cartcrafters";

    static JDBCDataSource dataSource;

    public static void init() throws SQLException {
        // Prevent re-initialization
        if (dataSource != null) return;

        dataSource = new JDBCDataSource();
        dataSource.setUrl(DB_URL);

        Statement stmt = dataSource.getConnection().createStatement();

        // Tables
        stmt.executeUpdate("CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");

        // Dummy Values
        stmt.executeUpdate("INSERT INTO users (name) VALUES ('John Doe')");

        // Setup ActiveJDBC
        ConnectionJdbcConfig conf = new ConnectionJdbcConfig("org.hsqldb.jdbcDriver", DB_URL, null);
        conf.setEnvironment("development");
        org.javalite.activejdbc.connection_config.DBConfiguration.addConnectionConfig(conf);


        withDb(() -> {
            new User().set("name", "Steve Johnson").saveIt();
            return null;
        });
    }

    public static void test() {
        int x = withDb(() -> {
            List<User> users = User.findAll();
            for (User user : users) System.out.println(user.get("id") + ": " + user.get("name"));
            return users.size();
        });
        System.out.println("Entries: " + x);
    }
}
